export enum DatabaseActions {
    Get = `Read`,
    None = `None`,
    Read = `Read`,
    List = `Read`,
    Fetch = `Read`,
    New = `Create`,
    Set = `Update`,
    Add = `Create`,
    Edit = `Update`,
    Patch = `Update`,
    Create = `Create`,
    Update = `Update`,
    Remove = `Delete`,
    Delete = `Delete`,
    Disable = `Disable`,
    Created = `Created`,
    Updated = `Updated`,
    Removed = `Deleted`,
    Deleted = `Deleted`,
}